# https://jupyterbook.org/customize/config.html

title: Query Me
author: BQ FUN

html:
  favicon: "favicon.ico"
  use_edit_page_button: true
  use_issues_button: true
  google_analytics_id: ""
  baseurl: ""

launch_buttons:
  thebe: true

repository:
  url: https://github.com/na0fu3y/theme-example
  branch: main
