on:
  push:
    branches:
    - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - run: pip install beakerx beakerx-kernel-sql jupyterlab jupyter-book

    - run: |
        jupyter labextension install @jupyter-widgets/jupyterlab-manager
        jupyter labextension install beakerx-jupyterlab

    - run: jupyter-book build .

    - uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
